### ISSUE TITLE
Add 'pshtml running in a container' example

### ISSUE THREAD

**Issue by Stijnc** [Stephanevg/PSHTML#119]
@Stephanevg , as discussed on twitter, a placeholder issue to add the docker and kubernetes example I used to the pshtml repo.

How would you like it to be structured?
Do I create a subfolder 'container' under 'example'?

the example would include the use of polaris and pshtml running in  a linux container on powershel core

**Comment by Stephanevg** [comment]
Hey @Stijnc did you got a chance to get this one done?

**Comment by Stephanevg** [comment]
Hey @Stijnc Qny news on this one? I was cleaning up old issues, and I would like to close this one (almost a year that it is open now)

**Comment by Stephanevg** [comment]
Closing as no response for a long time.
