### ISSUE TITLE
Discussion: Add support for Configuration

### ISSUE THREAD

**Issue by Stephanevg** [Stephanevg/PSHTML#153]
I would like to discuss how we could offer the possibility to PSHTML admins a way to configure the product.

I think mainly of having the possibility to:

- Configure log location
- Configure default file locations
- Configure Alternative paths (Additional template folders, additional logging places etc..)

I would like to open a discussion to:

Is there an existing module that we 'perhaps' have a dependency on?
If not, would it make sense to develop our own solution?

**Comment by bateskevin** [comment]
At the top of my head I would use a json file in the module directory where these values are saved. You could then provide a cmdlet to retrieve the information and one to change the information in the file.

A more simple option would be a .config in the moduledirectory --> edit with notepad :)

What do you think about that?

**Comment by Stephanevg** [comment]
Hmm, I was actually really considering the [PSFramework](https://github.com/PowershellFrameworkCollective). But I couldn't find out if:
1) PSFramework is crossplatform
2) Does it make sense to introduce a dependency on an another module?

I do think it maybe make sense to use some standard existing tool / module so that we can actually focus on what matters for us - The module it's self, and not spending too much time in re-inventing the wheel.

Like this, we would delegate the responsability to the maintainers of PSFramework, and we can focus in adding new features in PSHTML, and benefit from updates in the module, when they release new versions.

**Comment by bateskevin** [comment]
I see your point. For me it would depend on how much configuration is needed. If there are gonna be like 10 lines in that config file I would not introduce dependencies on other modules. If there there are more complex configs that should be possible it may aswell make sense to use an existing solution.

**Comment by Stephanevg** [comment]
After some more digging in PSFrameWork, I realized that it does far more that what I originally thought it would. As this might be great in some cases, In our particular case, I just needed to have one and single functionality: Config.

I couldn't something what would really answer my need (and really thought that PSFramework would answer it for logging and configuration) but I think we would be better off by developping our own implementnation as 
1) it would not be that of a hassel to write 
2) If we arrive in a pit, we can always reconsider PSframework (or perhaps another module).

As of the implementation, I think the proposal of @bateskevin using a JSON file is a good idea as it would be compatible on Windows & Linux (no issue with registry for example) and is a standard and well known format.

Talking about format, I would propose something like this:

```powershell
{
    "Configuration": {
        "Verbosity": "Normal"
    },
    "Logging": {
        "Path": "C:\\logging",
        "MaxFiles": 200,
        "MaxTotalSize": "5MB"
    },
    "Assets": {
        "Path": "$PSScriptRoot\\Assets"
    }
}
```
(There is probably a lot more to add, but I think this will be enough to start. pleaseShare ideas ! :)

**Comment by Stephanevg** [comment]
Hi all,

I just added a first draft of the ```configuration``` functionality. 

It respects what I mentionned in my comment above, but I'll summarize it again here:

1) The configuration file is expected to be located in the **Root of the module** and _must_ be called **PSHTML.Configuration.JSON**.
2) For the moment, it contains the following default values:
```Json
{
    "version":"1.0.0",
    "Configuration": {
        "Verbosity": "Normal"
    },
    "Logging": {
        "Path": "C:\\logging",
        "MaxFiles": 200,
        "MaxTotalSize": "5MB"
    },
    "Assets": {
        "Path": "Default"
    }
}
```

## How does it work?

When the module is imported, a variable called ```PSHTML_Configuration``` is made available to the module (currently, it is a global variable to eas debuging, but it might be better to have it private - To discuss).

Through that variable, we have access to an object (of type [ConfigurationFile]) which contains the configuration data from the **PSHTML.Configuration.Json** file.

We can access each of the following sections easily using the following methods:
- 'Configuration' --> GetGeneralConfig()
- 'Assets' --> GetAssetsConfig()
- 'GetLogConfig' --> GetLogConfig()

### Example:
```powershell
$PSHTML_CONFIGURATION.GetGeneralConfig()
```
![image](https://user-images.githubusercontent.com/6302961/50773806-15b1a680-1292-11e9-8a7b-81d87f2e8bb8.png)


## more details about Assets:

When the module loads, I look which Assets folders are present, and generate a Hashtable and assign it to the PSHTML_Configuration variable.
This allows us to easily find the place of where which asset is located.
To access the assets, I have added a method called ``` GetAsset() ```.
To return a specific asset, I added a overloaded metthod ```GetAsset($AssetName)```

In action it would like this:

![image](https://user-images.githubusercontent.com/6302961/50773363-f5cdb300-1290-11e9-9beb-4021bf8904b0.png)

And using the overload like this:

![image](https://user-images.githubusercontent.com/6302961/50773430-1f86da00-1291-11e9-8763-eb4a33a6744f.png)

I personally like the approach, as it will make the configuration information available to scripter in a very easy manner.

Please share your thoughts and insights with me on this approach, and additionally (of if you have no oppinion on it) participate by answering the following things:
- Naming (Name of variable, nodes in Configuration File, THE configuration file itself...)
- Do you see perhaps some Nodes / or information that you think is important in a config file missing in my example ? if yes, please share  your thoughts.
- Anything else?



> Code is available on the 'Configuration' branch here --> https://github.com/Stephanevg/PSHTML/blob/configuration/PSHTML/Classes/Private/Configuration.Ps1
The according pester tests are here --> https://github.com/Stephanevg/PSHTML/blob/configuration/Tests/Configuration.Tests.Ps1

**Comment by christophekumor** [comment]
Nothing special to say for the moment, all seem to be fine, i agree with your ideas.

**Comment by Stephanevg** [comment]
Notes and feedback:
From French Community (@fdibot)
- Add possibiltiy to Save values from Variable back to File (Add MEthod: SaveToFile() to Class ConfigurationFile).
- Support several File types for configuration files (EG: YAML). -> Add logic, that IF JSON file is found, it will load that one, NO JSON found, then Go for YAML).

**Comment by Stephanevg** [comment]
I have added on modification to the above:

Instead of queriey the $PSHTML_Configuration variable, the end users will need to use the cmdlet ``` Get-PSHTMLConfiguration```

It supports exact the same features as above (using the same methods).
More information is available in the comment based help of the function [here](https://github.com/Stephanevg/PSHTML/blob/master/PSHTML/Functions/Public/Get-PSHTMLConfiguration.ps1)

I have added the feature to master.
See PR here --> https://github.com/Stephanevg/PSHTML/pull/172

**Comment by ChendrayanV** [comment]
Can we consider MSI package? Some thing like below! 
[https://www.sapien.com/blog/2013/06/05/introducing-the-msi-wizard/](https://www.sapien.com/blog/2013/06/05/introducing-the-msi-wizard/)

**Comment by Stephanevg** [comment]
That is really a good idea @ChendrayanV !! Have you done this before? 
I know that the guys who maintain [AutomatedLab](https://github.com/AutomatedLab/AutomatedLab/releases) do it as well.

**Comment by ChendrayanV** [comment]
I haven;t tried myself - But I can experiment the possibilities for MSI and let you know. We need a Primal Studio or PowerShell studio (Sapien) product. Previous [Link ](https://www.sapien.com/blog/2013/06/05/introducing-the-msi-wizard/) for reference.  Thinking alternatives without third party tools.

**Comment by Stephanevg** [comment]
Hi,

I have merged my [local dev branch into dev](https://github.com/Stephanevg/PSHTML/pull/176). And will merge it into master soon and release version 0.7.1 of PSHTML. 

@ChendrayanV 
I think we are getting a bit off topic here, as this issue was track and discuss configuration. I will close this issue, and invite you to open a new one if you want to continue the discussion.

I like the idea of having an MSI package (and why not a Choco package?) but we need to keep in mind that the process of creating these packages must be limited in terms of external helper tools, and especially, the process must be easily automatable to be added to the Deployment section of our CI.

**Comment by Stephanevg** [comment]
Voila, I have merged everything where it should be.
Latest version is now 0.7.1 and it contains the 'configuration' section we discussed above.
![image](https://user-images.githubusercontent.com/6302961/51105292-e0084280-17e8-11e9-80be-33426fda8b42.png)

Closing ticket.
