### ISSUE TITLE
Add support for to pipe Objects and generate HTML tables

### ISSUE THREAD

**Issue by Stephanevg** [Stephanevg/PSHTML#16]
I have already started a function here --> https://github.com/Stephanevg/PSHTML/blob/master/Functions/Public/ConvertTo-HtmlTable.ps1 

Best would be to try to integrate it with Set-HtmlTag (If possible of course)

**Comment by Stephanevg** [comment]
Some more info:

The Cmdlet already work, but has a 'strange' behaviour when nested objects are present:

The following example highlights this:

```PowerShell
$a = Get-Process
$a[0].MainModule | ConvertTo-HTMLTable  | out-file .\woop.html -Force 
start .\woop.Html

# Have a look at 'FileVersionInfo'
$a[0].FileVersionInfo 
```

The nested objects breaks the formating of the table:

I am not sure how one could takle this. I see two options:
1) Expand the object and create another table recursivly. 
2) Call ToString() on the nested object
3) Other suggestions?

**Comment by bateskevin** [comment]
[Pull request](https://github.com/Stephanevg/PSHTML/pull/22) opened to address this issue
