### ISSUE TITLE
New-PSHTMLChartPieDataSet absent

### ISSUE THREAD

**Issue by Aratal** [Stephanevg/PSHTML#197]
### Subject of the issue
La fonction New-PSHTMLChartPieDataSet n'est pas présente.

### Steps to reproduce
Chargé le module (v 0.7.4) et utiliser la commande New-PSHTMLChartPieDataSet.
![version_pshtml](https://user-images.githubusercontent.com/11940282/52117477-1d0b6c00-2614-11e9-90ea-85022af64342.PNG)

### Actual behaviour
Lors de l'utilisation pour générer une page voici le retour : 
![bug_pshtml](https://user-images.githubusercontent.com/11940282/52117428-036a2480-2614-11e9-9d8c-f6cd959e3104.PNG)

**Comment by Stephanevg** [comment]
Merci d'avoir ouvert ce ticket @Aratal 

Le problem viens du fait que cette fonction (et d'autre d'ailleurs) sont dans le fichier des classes, et pas dans /functions/Public/$NomDefunction.ps1

![image](https://user-images.githubusercontent.com/6302961/52117750-d0746080-2614-11e9-8f4b-101ac800228f.png)


Possible solution:

Il faut déplacer toutes les fonctions des fichiers des classes dans des functions isolés dans Functions/public
