### ISSUE TITLE
Publish PSHTML to the PowerShell Gallery 

### ISSUE THREAD

**Issue by tylerl0706** [Stephanevg/PSHTML#21]
https://PowerShellGallery.com

It's the best way to share PowerShell modules with the community 😊

**Comment by Stephanevg** [comment]
Agreed. I would like to have CI implemented first. I track this [here](https://github.com/Stephanevg/PSHTML/issues/34)

**Comment by Stephanevg** [comment]
@tylerl0706 , PSHTML is now available on the gallery :)

**Comment by tylerl0706** [comment]
Awesome work!!
