### ISSUE TITLE
Form "target" shouldn't be mandatory

### ISSUE THREAD

**Issue by TylerLeonhardt** [Stephanevg/PSHTML#212]
### Subject of the issue

`target` is not mandatory in an HTML form so it shouldn't be required in PSHTML.

See: https://www.w3schools.com/tags/att_form_target.asp

towards the bottom is says `_self` is the default which means that `target` does not have to be specified.

### Steps to reproduce

```PowerShell
Form -Id uploadbanner -action AddTwitchDataFile -method post -Attributes @{ enctype="multipart/form-data" }
```

### Expected behaviour
`target` is not needed.

### Actual behaviour

```
cmdlet Form at command pipeline position 1
Supply values for the following parameters:
target
```

**Comment by Stephanevg** [comment]
Thank you SO much for reporting this @TylerLeonhardt . You have no idea what this can mean to me :)

In the mean time, I implemented a fix this morning which is available in this PR -> https://github.com/Stephanevg/PSHTML/pull/214

I removed the mandatory from the target parameter.
If target is **not** specified, it will default to target=_self.

is this an acceptable fix for you?

**Comment by TylerLeonhardt** [comment]
Perfect!! 😊

**Comment by Stephanevg** [comment]
great. this is live now on master and the gallery in version 0.7.10.

Please keep up the feedback. Supet much appreciated @tylerLeonardt
