### ISSUE TITLE
Missing 'form' parameter 'enctype'

### ISSUE THREAD

**Issue by TylerLeonhardt** [Stephanevg/PSHTML#213]
### Subject of the issue

as explained [here](https://www.w3schools.com/tags/att_form_enctype.asp) the `enctype` attribute is used to declare how form data should be encoded. This is needed if you're trying to generate a `form` that uploads files.

### Steps to reproduce
Look at `Form` function.

### Expected behaviour
It should have an `enctype` parameter.

### Actual behaviour
It doesn't have an `enctype` parameter.

I'm using `-Attributes` as a workaround but it would be nice to not have to use that!

**Comment by Stephanevg** [comment]
Hi @TylerLeonhardt Thank you SO much for opening this issue.

I have built the `-Attributes` parameter exactly for that purpose.
Thanks for reporting this. I'll work on it and make anothe release ASAP.

**Comment by Stephanevg** [comment]
Hi again,

I have added a dynamic parameter for enctype, which is only available when Method is set to Post.
These are the three acceptable values:
- "application/x-www-form-urlencoded"
- "multipart/form-data"
- "text/plain"
(I also updated the comment based help, and added pester tests to seal this down).

See PR here --> https://github.com/Stephanevg/PSHTML/pull/214

is this an acceptable solution for your @TylerLeonhardt ?

**Comment by TylerLeonhardt** [comment]
Perfect!!
