### ISSUE TITLE
Add ability to edit point attributes on a line chart.

### ISSUE THREAD

**Issue by ThePoShWolf** [Stephanevg/PSHTML#217]
### Add ability to edit Point attributes on the line graphs
First off, I love the charting in PSHTML! I'd also like if it was possible to edit the point attributes on a line chart.

Specifically, looking at the [Chart.js docs](https://www.chartjs.org/docs/latest/charts/line.html) they mention several attributes that I'd like to be able to set with PSHTML:

```text
pointRadius (this is hard coded to 4 in Class datasetline)
pointHitRadius
pointHoverRadius
```

### Steps to reproduce
Create a line chart and the script will contain:

```javascript
"pointRadius":4, ... "pointHitRadius":null, ... "pointHoverRadius":0
```

I'm happy to take this issue, but wanted to submit it before working on it.

**Comment by Stephanevg** [comment]
Hi @ThePoShWolf thank you SO much for opening this issue.
I am SO thrilled to the idea you live streaming this. I'll defenitley try to connect. 🤞 😃 

I agree with you, that it would be great this available, and I am so happy you want to work on this one 🎉 👍 

Do you have already an idea of how you want to implement this? (Have a look at the diagram here under before answering this question ;) )

> Also, on a side note: I realized I never created the Class diagram for the charting functionality, I have done this a few minutes ago, and you can have a look at the UML(ish) diagram here --> [Class Diagram](https://github.com/Stephanevg/PSHTML/blob/master/Code/Classes/003.pshtml.components.charts.png)
I think this really helps to have a good global understanding / overview of the solution.

**Comment by ThePoShWolf** [comment]
Hey! Glad to hear it. I can't emphasize enough how excited I was when I found PSHTML and saw that it could chart 😃

The ```datasetline``` class already has the properties, they just aren't parameterized. So I _think_ it is as simple as adding the parameters to ```New-PSHTMLChartLineDataSet``` and then setting them on the ```$DataChart``` object within that function like you already set the other properties.

In fact, just looking through it now, it might actually be a lot easier than I initially thought. We'll see!

Great idea on the diagrams. That helps a lot!

**Comment by Stephanevg** [comment]
Awesome @ThePoShWolf. I am really curious to see what you have built with PSHTML up until now. 👀 

Concerning the parameters, what do you think if we added Getters and setters on the DataSetLine class first, and reuse these ones in `New-PSHTMLChartLineDataset` (which will be filled using Parameters passed on cmdlet) ?

Like that, we could potentially reuse these in the future ( if needed of course)

**Comment by ThePoShWolf** [comment]
My first project is a pet project tracking some stats for a game that I play 😆 You can see how that is coming along here: http://utographs.com. If you look at one of the [longer charts](http://utographs.com/7-6_7-14.html) you can see how the points are all overlapping. That is what I'm trying to solve.

That entire site is all generated using PSHTML and hosted in an Azure storage account with static hosting enabled. Its not much at this point, but PSHTML makes it possible!

Yeah, that would work. Are you thinking along the lines of:

```PowerShell
$DataChart.SetPointRadius(0,4,4)
```

And then the method be something like:

```PowerShell
void SetPointRadius([int]$PointRadius,[int]$PointHitRadius,{int]$PointHoverRadius){
    #Code
}
```

And of course a corresponding

```PowerShell
PS> $DataChart.GetPointRadius()

PointRadius      : 0
PointHitRadius   : 4
PointHoverRadius : 4
```

Or something different?

**Comment by Stephanevg** [comment]
that is so cool to see the module in action.

I think that `if`you want to call the method `SetPointRadius`it should __only__ set the point radius.

I think that in your example, you are setting the `Properties` or `settings` don't you think?

It would then make sense that it c

```powershell
void SetPointSettings([int]$PointRadius,[int]$PointHitRadius,{int]$PointHoverRadius){
    
  $this.SetPointRadius([int]$PointRadius)
  $this.SetPointHitRadius([int]$PointHitRadius)
  #code...
}
```

What do you think?

Also, you were mentioning that it might be quicker then what you thought to fix this. You can perhaps also have a look / try to create the pester test for that method.

**Comment by ThePoShWolf** [comment]
Ah, good point. I'll use ```SetPointSettings``` or something similar.

And sure, I'm not all that good with Pester, but I'm always looking to improve. Would that be in: ```Chart.DatasetLine.Tests.ps1```?

**Comment by Stephanevg** [comment]
wow you are quick! Yeah that would be in that file.
btw, I have made some arrangements, so that I can join your live stream session tomorrow 🎉

**Comment by Stephanevg** [comment]
@ThePoShWolf Concerning the Pester tests, you can always generate them automatically using `Write-CUPesterTest` from [PSClassUtils](https://github.com/Stephanevg/PSClassUtils).

You will have to be carefull though, as it will generate the basic set of steps, overwriting the already existing tests.  So I'd recommend that __if__ you use it, you use it along these lines.

```Write-CUPesterTest -Path $SourcefileFullName -ExportFolderPath $FolderPath -AddInModuleScope PSHTML ```

>I am planning to add functionality to generate tests only for a specific Class / Constructor / Method but I am not quite there yet.

**Comment by ThePoShWolf** [comment]
That is sweet. I'll have to spend some time with PSClassUtils now 😃

**Comment by Stephanevg** [comment]
Adding this tweet https://twitter.com/Stephanevg/status/1106720563467300864?s=19 as i think it is a part of this conversation. 
cc: @theposhwolf

**Comment by Stephanevg** [comment]
I am close to merging this one. 
Recently, I added the support for a few new chart types. See [this tweet](https://twitter.com/Stephanevg/status/1152849190617255937) . One that I can think that could benefit of this feature as well is `PolarArea` chart.


Do you think it would make sense @ThePoShWolf (I opened a new issue to track it [On this link](https://github.com/Stephanevg/PSHTML/issues/254)

**Comment by Stephanevg** [comment]
Hey I actually merged this one, and fixed the tests to work on PSCore and windows. thank you again SO MUCH for your work @ThePoShWolf  Super appreciated!!

Looking forward to work again with you. (Perhaps on curl2PS? ;) )
