### ISSUE TITLE
Output th in ConvertTo-PSHTMLTable in thead

### ISSUE THREAD

**Issue by datenschieber** [Stephanevg/PSHTML#222]
ConvertTo-PSHTMLTable outputs td tags in thead. Wouldn't it be better to output th tags?

Steps to produce:
```
Html {
    Body {
        [PSCustomObject] @{
            Key1 = "Value1"
            Key2 = "Value2"
        } | ConvertTo-PSHTMLTable -Properties Key1, Key2
    }
}
```

Current output:
`<html ><Body ><Table ><thead ><tr ><td >Key1</td><td >Key2</td></tr></thead><tbody ><tr ><td >Value1</td><td >Value2</td></tr></tbody></Table></Body></html>`

Better output:
`<html ><Body ><Table ><thead ><tr ><th >Key1</td><th >Key2</td></tr></thead><tbody ><tr ><td >Value1</td><td >Value2</td></tr></tbody></Table></Body></html>`

**Comment by Stephanevg** [comment]
Thanks @datenschieber for opening this issue. this one will be part of the next release, as it was added in #229
