### ISSUE TITLE
Add $PSScriptRoot/Includes to supported include path

### ISSUE THREAD

**Issue by datenschieber** [Stephanevg/PSHTML#224]
The dynamic parameter should search for a `Includes` folder in the location of where the script is currently executing (`$PSScriptRoot`).
It should offer tab completion for the parameter `$Name` for every file that finishes with .ps1.
The tab completion should be displayed without the extension.

Currently it seems that only `$PSModuleRoot/Includes` is supported.

Documentation already says (but it doesn't work this way):

> Include  files must be located in the following location:
> $PSScriptRoot\Includes

**Comment by Stephanevg** [comment]
Hi @datenschieber ,

I was off for paternity leave, so sorry this took a while to write you back :)
Thanks for reporting this issue. I think you are right, it searches directly in the $PsModuleRoot/includes. 
I'll have a look it asap

**Comment by Stephanevg** [comment]
This is actually going to be a pretty big change if I want to this correctly.

For that, I have drafted requirements and a design here -> https://github.com/Stephanevg/PSHTML/issues/240

**Comment by Stephanevg** [comment]
Design is done.
Feature has been implemented and merged into dev.
Tracking pester tests here -> 
https://github.com/Stephanevg/PSHTML/issues/243

**Comment by Stephanevg** [comment]
Closing this ticket, as the functionality has been merged into the dev branch (It is called `PSHTML Asset / includes locations`).

Thanks for reporting this one @datenschieber 
It will be availalbe in version 0.8.0 when I finish all the open issues from this milstone https://github.com/Stephanevg/PSHTML/milestone/1
