### ISSUE TITLE
Externalize function + from psm1 to seperate files

### ISSUE THREAD

**Issue by Stephanevg** [Stephanevg/PSHTML#245]
In this PR https://github.com/Stephanevg/PSHTML/pull/241

@wightsci added Get-PSHTMLColor and expanded the [COLOR] class which are located in pshtml.ps1

These function + class will beed to be externalize  to a file named `Get-PSHTMLColor.ps1`  in `Code\Functions\public`

The expanded class will need to be put in the same file as the function, at  the top of the file, to simplify testing (Class is located here 003.pshtml.components.charts.ps1 )

One done, the script ´.\CI\03_Build.ps1´ should be called once to rebuild the module.

**Comment by wightsci** [comment]
Please see PR #247

**Comment by Stephanevg** [comment]
Thanks for your PR, since it closed, and the files are moved, I'll close this one.
