### ISSUE TITLE
Are HTML columns supported?

### ISSUE THREAD

**Issue by JRSerjeant** [Stephanevg/PSHTML#295]
### Subject of the issue
Are HTML columns supported?

### Steps to reproduce
```
div -Class "row" {
                div -Class "column" {"This is column 1"}
                div -Class "column" {"This is column 2"}
                }
```

### Expected behaviour
The text would appear in two different columns

### Actual behaviour
Test appears on top of each other.

**Comment by Stephanevg** [comment]
Hi @JRSerjeant,


In a nutshell, PSHTML outpus HTML, which is the same HTML5 you can find in any other web document. 
A column per see, as i understood it, is nothing else than a CSS property. CSS is support by PSHTML, so to answer you question, yes, column would be supported, but it seems like you are not using it correctly.

You will need to declare a CSS class, and assign that class to the the div (or any other element where you would like to have it applied to) via the ```-Class``` property.

An example is available on the [mozilla website](https://developer.mozilla.org/en-US/docs/Web/CSS/columns#examples )

For your case, you will can create a new folder called 'includes' in the same location where the script is located, add a new test.css file, and important your css file in the header section of your html document using the ```include``` function.

From that point, you should be able to use it as any other custom CSS property in your html document.
I hope this helps :)

Cheers!
