### ISSUE TITLE
HTML is on a single line. Need line breaks

### ISSUE THREAD

**Issue by quickbasic22** [Stephanevg/PSHTML#296]
HTML is on a single line. Need line breaks

**Comment by Stephanevg** [comment]
Hi @quickbasic22 
this is a problem without beeing one actually. 
If you open a generated HTML output from PSHTML in any IDE, that IDE will automatically format the code for you.
also, having the HTML on one single line is a valid form of HTML document, so technically there is nothing wrong with that.
