### ISSUE TITLE
Where is normalize.css?

### ISSUE THREAD

**Issue by eliassal** [Stephanevg/PSHTML#304]
### Subject of the issue
I see in all examples the usage of a css file called normalize.css

### Steps to reproduce
Searched for normalize.css but was not able to find it

### Expected behaviour
normalize.css to be available to run the demos

### Actual behaviour
No normalize.css file in the repo

**Comment by Stephanevg** [comment]
Hi @eliassal 
You actually don't need to have this file. It was used just as example to create a link element.
