### ISSUE TITLE
Add tests to ensure that scriptblock expansion of nested HTML elements works

### ISSUE THREAD

**Issue by Stephanevg** [Stephanevg/PSHTML#65]
### Subject of the issue
See title

## Implementation

See [DataList.Tests.Ps1](https://github.com/Stephanevg/PSHTML/blob/master/Tests/datalist.tests.ps1)
```powershell
it 'Testing: -Content Parameter should expand child elements' {
            
            $string2 = datalist {option -value "Volvo" -Content "Car" }
            $String2 = $string2 -join ""
            
                $string2 -match '^.*>.*<option value="Volvo".*<.*' | should be $true
            
        }
```

This should probably need to be addedmost (all?) pester tests.
The first step, would be to write a short script, to identify which of the tests already have that it block, and which don't, to understand the scope of the issue.

**Comment by christophekumor** [comment]
hmm c'ant remember .. i think yes, i had no issue with tests i made

**Comment by Stephanevg** [comment]
done. closing
