### ISSUE TITLE
HTML Tables - Consider integrating PSHTMLTable in PSHTML

### ISSUE THREAD

**Issue by Stephanevg** [Stephanevg/PSHTML#94]
We already have a ConvertTo-HTMLTable but perhaps it would make sense to consider this one as well:

https://github.com/RamblingCookieMonster/PSHTMLTable/

It is under an MIT licence, so we could potentialy integrate it into PSHTML.

@christophekumor is this something you would like to look in too ?

**Comment by christophekumor** [comment]
yep i'll have a look at this !
do you want to add functionality to `ConvertTo-HTMLTable` or create a new function ?

**Comment by Stephanevg** [comment]
To avoid to many dependencies, will not do.
