### ISSUE TITLE
Adding function for symbols - Nice to have - Opinions required

### ISSUE THREAD

**Issue by ChendrayanV** [Stephanevg/PSHTML#97]
# Nice to have - Opinions required
Will it be good idea to add a function to insert symbols. Let me know your thoughts. 
# What symbols does in HTML ?
For example I need to show some catchy texts like "I ♥ PSHTML" - Here the heart symbol is rendered by a code &hearts;
# How we get it done in PSHTML?
Sample Code is below 

```PowerShell
function symbol{

    param (
        [Parameter(Mandatory)]
        [ValidateSet('spades','clubs','hearts', 'diams')]
        $Name
    )

    process {
        switch($Name) {
            "spades" {
                "&spades;"
            }
            "clubs" {
                "&clubs;"
            }
            "hearts" {
                "&hearts;"
            }
            "diams" {
                "&diams;"
            }
        }
    }
}
# Use case is below

```PowerShell
p -content {
    "I "
    symbol -Name hearts
    " PSHTML"
}


# Renders HTML 
```HTML
<p>
    I
    &hearts;
    PSHTML
</p>

Your opinions and suggestions are highly appreciated!

**Comment by Stephanevg** [comment]
Hi @ChendrayanV 
I LOVE the idea of this! For me, the design of this cmdlet looks good. I was just thinking about the naming of the cmdlet. Actually, of naming of the cmdlet in general in this module.

Perhaps the cmdlet 'symbol' could be an `alias` for `Set-PSHTMLSymbol`. It will alloow users to have the ability implement easily a well know HTML symbol, and allows us to add a layer of abstraction for the end user, which will allow us to modify (rename?) the cmdlet if needed.

It would be nice to be able to support a scenario with pipeline input like this one:

```powershell

#for when the symbols to created are caluculated on the fly, or coming from an external source

"Hearts","Diamonds","Clubs" | Set-PSHTMLSymbol

```

What do you think?

**Comment by christophekumor** [comment]
Nice idea ! about cmdlet name , `Write-PSHTMLSymbol` or `Use-PSHTMLSymbol` would be better no ?

**Comment by Stephanevg** [comment]
I actuall think that 'Write-PSHTMLSymbol' is quite good. What do you think @ChendrayanV ?

**Comment by Stephanevg** [comment]
This has been added.Closing issue.
