### ISSUE TITLE
Change the way the module builds 

### ISSUE THREAD

**Issue by bateskevin** [Stephanevg/PSHTML#98]
### Change the way the module builds
The module is getting to big to dot source all the functions. 

Part of a build should be to generate the psm1 file with all the Functions and (eventually) classes in it.

This will increase the import time of the module drastically.

**Comment by Stephanevg** [comment]
Completley agree on this one. I wanted to do this one already before, simply didnt got to it yet.

I think some things need to be taken into consideration:

Classes need to be loaded in order. I know we don't have any yet, but this will change in the near feature.

Therefore, the build script should read the order of the classes to load from a psd1 file.

here is an example of build script from Christ Gardner  we could use as starter: https://github.com/FrPSUG/Presentations/blob/master/20180915-Module_Development_Best_Practices(Chris_Gardner)/build.ps1 

As a general note: The build Script should be completley independant of any external module to be able to build the module.

**Comment by ChendrayanV** [comment]
This request is very valid. When we are building static web pages, module load time is not that important. But, to render it on web page, it is much focused. Due to module load time the PSHTML used in node.js takes 58 seconds to render the output. 

@Stephanevg @bateskevin

**Comment by Stephanevg** [comment]
Implemented.
