### ISSUE TITLE
Cmdlet Prefix naming

### ISSUE THREAD

**Issue by Stephanevg** [Stephanevg/PSHTML#99]
Up until now, we have been creating mostly just HTML tags.
I would like to discuss the prefix of the cmdlets, which are **not** tags.

Which are:  (I could be missing a few) 

- ConvertTo-HTMLTable
- Set-HTMLTag
- Get-HTMLTemplate
- Install-PSHTMLVsCodeSnippet

The problem I see here, is that we have difficulties to identify quickly which functions are from the PSHTML module, and which ones are really part of the powershell language (such as `ConvertTo-HTML`).

To differenciate this, I would suggest we rename all the **non-tags** cmdlets with a specific prefix,, and use that same prefix for future **non-tag** functions.
I would tend to use ```PSHTML``` if you guys don't see anything against it. (or have a better Idea).

This would result in something like this:

- ConvertTo-PSHTMLTable
- Set-PSHTMLTag
- Get-PSHTMLTemplate
- Install-PSHTMLVsCodeSnippet

Let me know what you guys think of this (@christophekumor @christophekumor @ChendrayanV @bateskevin )

**Comment by christophekumor** [comment]
This is a good idea, and for auto completion it's fast, just get-psh...

**Comment by Stephanevg** [comment]
All Cmdlets tht are **not** tags will contain: 'PSHTML' as their prefix (See examples above).
